services:
  - type: web
    name: corp-site
    env: node
    region: frankfurt
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
